### ISSUE TITLE
Dom Nodes closes prematurely on recursion

### ISSUE THREAD

**Issue by afidegnum** [rust-scraper/scraper#162]
While traversing, the html tags were malformed on both while and for loops. 

you can see the example at: the `body` and other nested tags closed unexpectedly, 

https://github.com/SycaPerse/sytags/blob/main/src/bin/sytree.rs

can you please look into it?

**Comment by LoZack19** [comment]
Please @afidegnum , could you provide what you get and what you expected?

**Comment by LoZack19** [comment]
[This](https://paste.debian.net/1327763/) is what I get. What is the problem in here?

**Comment by cfvescovo** [comment]
@afidegnum Looks like you are using an old scraper release. Update it, retry and let us know

**Comment by cfvescovo** [comment]
I am closing this, @afidegnum feel free to reopen if you have new info
