### ISSUE TITLE
How to deal with html elements embedded into text

### ISSUE THREAD

**Issue by Tim-C1** [rust-scraper/scraper#216]
Hi all, I currently doing well with this excellent crate. I would like to ask for some suggestions for the following scenario:

```html
<pre>
...
some texts <b>xxx</b> <a href=xxx>xxx</a> some texts
...
</pre>
```
In this case the "body" of the `<pre>` element contains some texts and some elements embedded into it, I would like to  get the whole `some texts <b>xxx</b> <a href=xxx>xxx</a> some texts` as a just one html text. Is there any convenient way to do this?

**Comment by Maia-Everett** [comment]
If you're looking to retrieve an element's inner HTML as a `String`, you can use `ElementRef`'s `inner_html()` function.

**Comment by Tim-C1** [comment]
> If you're looking to retrieve an element's inner HTML as a `String`, you can use `ElementRef`'s `inner_html()` function.

Yeah, my current solution is to iterate all siblings of the node just before the html fragment that I'm interested in, then call `inner_html()` or just get it's text; However, some of the html elements embedded within the text node also has children, also I think the iteration is a bit expensive here.
