### ISSUE TITLE
Making the library `Sync`

### ISSUE THREAD

**Issue by YouKnow-sys** [rust-scraper/scraper#217]
currently because we have things like `OnceCell` inside `Element` scraper isn't `Sync` and because of that we'll have a hard time using it inside async codes, it would be nice if we used `OnceLock` instead of `OnceCell` by default, or if the overhead is not acceptable just put it behind a feature flag just like `atomic`

**Comment by cfvescovo** [comment]
Closing this as not planned. @YouKnow-sys reopen this if you think there is something @adamreichold did not address in his response
